### ISSUE TITLE
Questions about degraded file.

### ISSUE THREAD

**Issue by leoscribit** [google/visqol#17]
Hello, 
Could you share detailed procedures about how to collect degraded files.

I checked on Visqol tutorial that "degraded files" must be: "48k sample rate WAV file that will be compared to the reference audio."

So, once I need to compare performance of different codecs like (mp3, AAC, OGG, FAAC, Flac etc...), AND once I have a reference audio file (wav format, stereo, 48k). What should I do to? 
How can I get MOS scores of files using mp3 codec, for example?
Do I need to convert the reference audio file to mp3 and after that, revert back to wav form?
what tool is recommended to getting degraded file?

Thanks in Advance.

**Comment by mchinen** [comment]
Hi,
Yes, you should decode your MP3 or other codec to wav and resample to 48khz for the default audio mode (or 16khz for speech mode).  I typically use ffmpeg or sox command line interface for this, but other tools should be able to do this too.  ffmpeg should allow you to combine the decode and resample step into a single command.

**Comment by leoscribit** [comment]
So, I need to do as below:

Reference audio (WAV format, stereo, 48k) -----> code Reference audio to Ex.: MP3 file 

So, I need to decode the MP3 file (I've get from Reference file) to wav form again. 

Is it correct?

**Comment by mchinen** [comment]
Yes, that's correct.
