### ISSUE TITLE
pffft repo down

### ISSUE THREAD

**Issue by serkansulun** [google/visqol#18]
I received the following error during build.

ERROR: An error occurred during the fetch of repository 'pffft_lib_linux':
   java.io.IOException: Error downloading [https://bitbucket.org/jpommier/pffft/get/29e4f76ac53b.zip] to /home/user/.cache/bazel/_bazel_user/631aac0edc06f05dddb4a0ea29b61903/external/pffft_lib_linux/29e4f76ac53b.zip: GET returned 403 Forbidden

Looks like https://bitbucket.org/jpommier is down.

**Comment by FeargusOG** [comment]
I submitted a [PR](https://github.com/google/visqol/pull/19) to update the `pffft` repo. 

Unfortunately, I only have access to a linux machine at the moment for testing, so I only updated the linux build. If you are using a windows machine, you should be able to get it building by copying the changes I made.

I should have access to a windows machine in the next week or so. I can submit a windows PR at that point. If you get it building on windows in the meantime, feel free to submit the PR either!

**Comment by FeargusOG** [comment]
@mchinen I changed the repo to use a mirror of the original lib we were using - I expect everything should be fine from a license perspective therefore; but I said I'd flag that to you.

**Comment by Yolanda-Gao** [comment]
I met a similar error when built: //:visqol_lib depends on @pffft_lib_linux//:pffft_linux in repository @pffft_lib_linux which failed to fetch. no such package '@pffft_lib_linux//': java.io.IOException: Error downloading [https://bitbucket.org/jpommier/pffft/get/29e4f76ac53b.zip] to /home/yolandagao/.cache/bazel/_bazel_yolandagao/f5a0b626f305c308c95db98eb750782b/external/pffft_lib_linux/29e4f76ac53b.zip: GET returned 404 Not Found

**Comment by Yolanda-Gao** [comment]
NVM, I used the new number of the zip at https://bitbucket.org/jpommier/pffft/downloads/ to replace the one in WORKPLACE and commented the sha number. It just built successfully.

**Comment by whlteXbread** [comment]
Thanks for that PR @FeargusOG — I ended up needing to build (on linux) again and was able to do so thanks to your changes.

When I'm back at my windows machine sometime this week I'll try building again on Windows with this change.

**Comment by mchinen** [comment]
PR #19  merged, and looking at the feedback here, marking closed.

**Comment by whlteXbread** [comment]
I just rebuilt using the latest `master` on Windows and can confirm a successful build, for what it's worth.

**Comment by mchinen** [comment]
Thanks for the update @whlteXbread
