### ISSUE TITLE
Fail to build on Windows

### ISSUE THREAD

**Issue by PeiqiXu** [google/visqol#32]
Hi

I have tried to build Visqol on Windows 10 but got an error message with Bazel:

```
ERROR: C:/visqol-master/BUILD:36:11: //:visqol_lib depends on @armadillo_headers//:armadillo_header in repository @armadillo_headers which failed to fetch. no such package '@armadillo_headers//': java.io.IOException: Error downloading [http://sourceforge.net/projects/arma/files/armadillo-9.860.2.tar.xz] to C:/users/peiqi/_bazel_peiqi/d3jan4lu/external/armadillo_headers/armadillo-9.860.2.tar.xz: Redirect loop detected
ERROR: Analysis of target '//:visqol' failed; build aborted: Analysis failed
INFO: Elapsed time: 129.077s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (34 packages loaded, 278 targets configured)
    currently loading: @com_google_protobuf//
```

Bazel version is 3.5.0 (also tried 3.7.0)
Visual Studio 2019

Thanks for your help.

**Comment by mchinen** [comment]
The error is that for some reason your computer isn't able to download that armadillo URL.  I was able to with wget.  However I noticed that when using a browser it behaves differently and goes to a download page.  I'm not sure what the correct fix is here, but it would be nice to use a github solution instead if it existed (from a cursory glance the main project isn't on github).
Still, others have been able to build for windows, so maybe this is something else related to the local environment.  Please let me know if it starts working, or if others see this as well.

**Comment by PeiqiXu** [comment]
Though the bazel build process failed, I could open this armadillo URL from browser and download it manually. 
I uploaded it to a github, and changed the armadillo URL address in WORKSPACE. It worked.
