### ISSUE TITLE
Audio mode vs Speech mode and macos install

### ISSUE THREAD

**Issue by justwong99** [google/visqol#36]
Would audio mode generally be used for audio files other than speech (ex. a piano recording)? And speech mode only for people talking?

Additionally, I can't find any installation instructions for macos.

Thanks

**Comment by mchinen** [comment]
Hi there,

> Would audio mode generally be used for audio files other than speech (ex. a piano recording)? And speech mode only for people talking?
Yes, that's correct.  

> Additionally, I can't find any installation instructions for macos.
These are the same as the linux instructions - you can build from source.  There aren't any binary releases yet.  We should update the readme to indicate that.

**Comment by justwong99** [comment]
thank you.
