### ISSUE TITLE
Getting error - no such package '@com_google_protobuf//

### ISSUE THREAD

**Issue by zhangxiang88** [google/visqol#37]
I'm trying to build ViSQOL with following command - bazel build :visqol -c opt, but I'm getting the following error

ERROR: no such package '@com_google_protobuf//': java.io.IOException: Error downloading [https://github.com/protocolbuffers/protobuf/releases/download/v3.11.1/protobuf-all-3.11.1.tar.gz] to /private/var/tmp/_bazel_n689415/9b94f57562fb1bf28a7df8c596c92f3e/external/com_google_protobuf/temp9151135432370956210/protobuf-all-3.11.1.tar.gz: connect timed out
INFO: Elapsed time: 55.329s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

I'm running on Mac with Bazel version as bazel 3.7.2-homebrew and I'm able to download if I paste the URL (https://github.com/protocolbuffers/protobuf/releases/download/v3.11.1/protobuf-all-3.11.1.tar.gz) into the browser directly.

**Comment by mchinen** [comment]
I wasn't able to replicate this on mac from HEAD.

This does seem to be a networking issue.
One possibility is if you have some network sandbox/firewall tools that work per-app, and it is limiting bazel (or whatever process bazel starts to download), but it is not limiting your web browser.

**Comment by zhangxiang88** [comment]
Thank you Mchinen, I will look into it.

**Comment by mchinen** [comment]
Marking resolved.
