### ISSUE TITLE
Use of Visqol in lieu of Polqa

### ISSUE THREAD

**Issue by abouillot** [google/visqol#46]
Hi,

I'm looking into Visqol to be used as replacement/complement of Polqa

I have several campaigns consisting of various calls in and out with the recorded samples.

When performing the audio analysis with Polqa system, I can correlate the MOS result with the audio - i.e. bad score when the sound is degraded, good ones when the audio is of good quality.

When using Visqol as a drop down replacement, I don't see this correlation. I have scores in a center zone (~2 ish) for most of the samples, including when the audio sample is 'blank' between calls - i.e. no audio - or some with good quality (scored a 4+ by Polqa).

For the silence part, I would expect a score at 0.00 or close to 1.0 as given by Polqa.

The command line used is:
`visqol --degraded_file /share/record.210317-114801.wav --reference_file /share/French_SWB_f1s3_m1s3_8s.wav`

When using the --use_speech_mode modifier, the gap between a silence sample and a voice sample widen, with the silence score being lower, but significantly higher than expected. (1.45 vs 0.0 or close to 1.0).

What would be the appropriate way to use Visqol as a Polqa replacement?

Thanks

**Comment by AlexGrs** [comment]
Hello @mchinen . Can you elaborate a bit more on the feature that could help expand to more cases? We are trying to use VISQOL to also get Voice Quality MOS for some files during calls on Mobile networks or Applications like Google Meet, Whatsapp, Skype, etc. 

So far when using speech mode with reference files of 8s at 8kHz containing voice and silences, we have results that are a bit troubling: 
* a 4+ MOS Score using POLQA gives a 2.7 using VISQOL in SpeechMode.  Without using speech mode the results then are better around 3.7.

**Comment by abouillot** [comment]
Hi,

Here are two 2 minutes calls POLQA/VIQOL scores. When POLQA score is empty it is 1.000 or bellow (0.0) and corresponds to silence before and after the calls.

Surprisingly, better the POLQA score is, lower the VISQOL is - or so.

Call 1 - average

File|way|POLQA|VISQOL
-----|---|----|------
record.210409-124052.wav | 21 |		| 2.7074
record.210409-124101.wav |  12 |		| 2.55687
record.210409-124110.wav|21|		|2.75289
record.210409-124119.wav|12|1.0530	|2.82122
record.210409-124128.wav|21|2.7082	|3.31637
record.210409-124137.wav|12|3.7080	|3.0016
record.210409-124146.wav|21|2.3382	|3.22676
record.210409-124155.wav|12|3.5312	|3.0098
record.210409-124204.wav|21|2.7734	|3.28128
record.210409-124213.wav|12|3.7049	|3.06806
record.210409-124223.wav|21|2.7332	|3.23638
record.210409-124232.wav|12|3.6810	|3.16664
record.210409-124241.wav|21|2.5656	|3.30823
record.210409-124250.wav|12|3.2510	|3.0185
record.210409-124259.wav|21|2.9312	|3.31171
record.210409-124308.wav|12|3.5160	|3.06571
record.210409-124317.wav|21|2.3938	|3.24501
record.210409-124326.wav|12|		|2.55734
record.210409-124335.wav|21|		|2.65343
record.210409-124344.wav|12|		|2.55706
record.210409-124353.wav|21|		|2.91594
 
Call 2 - Good quality

File|way|POLQA|VISQOL
-----|---|----|------
record.210409-135757.wav|21|		|2.28432
record.210409-135806.wav|12|		|2.55632
record.210409-135816.wav|21|		|2.82872
record.210409-135825.wav|12|		|2.56238
record.210409-135834.wav|21|3.4681	|2.24964
record.210409-135843.wav|12|4.2896	|2.34882
record.210409-135852.wav|21|4.2205	|2.24262
record.210409-135901.wav|12|3.5310	|2.20133
record.210409-135910.wav|21|4.2683	|2.52217
record.210409-135919.wav|12|4.1675	|2.56467
record.210409-135928.wav|21|4.1980	|2.0876
record.210409-135937.wav|12|4.0073	|2.66254
record.210409-135946.wav|21|4.1742	|2.0642
record.210409-135955.wav|12|4.1084	|2.70553
record.210409-140004.wav|21|4.2426	|2.28844
record.210409-140013.wav|12|4.2543	|2.55737
record.210409-140022.wav|21|4.1527	|2.26108
record.210409-140031.wav|12|		|2.29483
record.210409-140040.wav|21|		|2.56125
record.210409-140049.wav|12|		|2.54917
record.210409-140058.wav|21|		|2.72278

The samples arein SWB, as using IMS.

**Comment by mchinen** [comment]
@abouillot and @AlexGrs Just to point out, you should be resampling all of your files to 16kHz before feeding them to ViSQOL, even if they are originally in narrowband or SWB.

@AlexGrs the feature I'm talking about uses deep lattice networks to handle more cases.  One thing that we find is that the current model doesn't generalize very well, and this should help somewhat.  You could also retrain directly on the model.
Before the DLN model is released, you might check to see if the ViSQOL scores have a meaningful correlation with your subjective scores - in that case the absolute value might not map well.

@abouillot If this still happens after using 16kHz files, the speech model may not work for your case.  Do you mind sharing what the case is?  Denoising or speech enhancement is a case that ViSQOL isn't able to handle.

**Comment by sevanabiz** [comment]
Have you tried Sevana AQuA?
