### ISSUE TITLE
Question about --batch_input_csv, --results_csv and --output_debug commands.

### ISSUE THREAD

**Issue by leodixit** [google/visqol#49]
Using this command as example: bazel-bin\visqol.exe --batch_input_csv "input.csv" --results_csv "results.csv" --output_debug "debug.json"

Can you check if command bellow is correct?

bazel-bin\visqol.exe --batch_input_csv "C:\AudioQuality\visqol-master\testevisqol\input.csv" --results_csv "C:\AudioQuality\visqol-master\testevisqol" --output_debug "C:\AudioQuality\visqol-master\testevisqol" --use_speech_mode --verbose

I'm not sure how this feature works...

I have created a input.csv file with following structure:
reference, degraded
path_reference1.wav, path_degraded1.wav
path_reference2.wav, path_degraded2.wav ...

Regarding results.csv and debug.json - are there files created automatically? Cause on the command I've mentioned below, I've just point a path folder.

Can you help me?

Thank you and Regards.

**Comment by FeargusOG** [comment]
Hi @leodixit ,

They way it currently works, you need to specify the filename for your `results_csv` and `output_debug` files. These files _do not_ already need to exist; visqol will create them for you. So, your command should look something like:

```
bazel-bin\visqol.exe --batch_input_csv "C:\AudioQuality\visqol-master\testevisqol\input.csv" --results_csv "C:\AudioQuality\visqol-master\testevisqol\results.csv" --output_debug "C:\AudioQuality\visqol-master\testevisqol\debug.json" --use_speech_mode --verbose
```

But this raises the question of whether that is desired behaviour? As it currently stands, it seems to fail silently - which is definitely not desired behaviour anyway! My assumption would be that if a dir is provided visqol should create the files in the provided dir using default filenames. Do you agree @mchinen ? If so, I'm happy to make that change.

**Comment by mchinen** [comment]
@FeargusOG I agree that failing silently is a bug.  I think it would be acceptable to fail with error but preferable to handle directories as you suggest.  I guess the directory checking isn't done because there wasn't a standard cross platform way of doing this in C++ when this code was originally written.  https://github.com/gulrak/filesystem might be useful here (preferred over std::filesystem since it has support in android NDK).

**Comment by leodixit** [comment]
Hi @FeargusOG  and @mchinen

Good news!
It works now.

Maybe there was something wrong on the input.csv file I was using on. I double checked and everything is working properly now.

Besides, I've got your point and completely agreed about silently failures/errors.

Anyway, Thanks a lot
