### ISSUE TITLE
Unit Tests Failing on Windows with File Not Found/File Missing Errors

### ISSUE THREAD

**Issue by iUnknwn** [google/visqol#50]
Hi, 

While I'm able to build the current version of visqol on Windows, when I run `bazel test all_unit_tests` from the root project directory (containing the workspace file), the test suite appears to be failing:

```
//:commandline_parser_test                                               FAILED in 0.3s
//:gammatone_spectrogram_builder_test                                    FAILED in 0.3s
//:misc_audio_test                                                       FAILED in 0.3s
//:vad_patch_creator_test                                                FAILED in 0.3s
//:visqol_api_test                                                       FAILED in 6 out of 15 in 0.6s
  Stats over 15 runs: max = 0.6s, min = 0.3s, avg = 0.5s, dev = 0.1s
//:visqol_manager_test                                                   FAILED in 12 out of 15 in 0.5s
  Stats over 15 runs: max = 0.5s, min = 0.3s, avg = 0.4s, dev = 0.1s

Executed 17 out of 17 tests: 11 tests pass and 6 fail locally.
```

Looking into the failed test logs, I see notes like this (from misc_audio_test):
```
[misc_audio.cc : 98] RAW: Could not find file testdata/clean_speech/CA01_01.wav.
```
I can confirm the wave files are in the appropriate testdata directory under the project root. For reference, here is the output of a `tree` command for the testdata dir:

```
C:\GITPROJECTS\VISQOL\TESTDATA
│   BUILD
│
├───alignment
│       degraded.wav
│       reference.wav
│
├───clean_speech
│       CA01_01.wav
│       transcoded_CA01_01.wav
│
├───conformance_testdata_subset
│       BUILD
│       castanets48_stereo.wav
│       contrabassoon48_stereo.wav
│       contrabassoon48_stereo_24kbps_aac.wav
│       glock48_stereo.wav
│       glock48_stereo_48kbps_aac.wav
│       guitar48_stereo.wav
│       guitar48_stereo_64kbps_aac.wav
│       harpsichord48_stereo.wav
│       harpsichord48_stereo_96kbps_mp3.wav
│       moonlight48_stereo.wav
│       moonlight48_stereo_128kbps_aac.wav
│       ravel48_stereo.wav
│       ravel48_stereo_128kbps_opus.wav
│       README
│       sopr48_stereo.wav
│       sopr48_stereo_256kbps_aac.wav
│       steely48_stereo.wav
│       steely48_stereo_lp7.wav
│       strauss48_stereo.wav
│       strauss48_stereo_lp35.wav
│
├───example_batch
│       batch_input.csv
│
├───filtered_freqs
│       guitar48_stereo_10k_filtered_freqs.wav
│
├───long_duration
│   └───1_min
│           guitar48_stereo_deg_1min.wav
│           guitar48_stereo_deg_25s.wav
│           guitar48_stereo_ref_1min.wav
│           guitar48_stereo_ref_25s.wav
│
├───mismatched_duration
│       guitar48_stereo_middle_2sec_cut.wav
│       guitar48_stereo_middle_50ms_cut.wav
│       guitar48_stereo_x2.wav
│
├───non_48k_sample_rate
│       guitar48_stereo_44100Hz.wav
│
├───short_duration
│   ├───10000_sample
│   │       guitar48_stereo_10000_sample.wav
│   │
│   ├───1000_sample
│   │       guitar48_stereo_1000_sample.wav
│   │
│   ├───100_sample
│   │       guitar48_stereo_100_sample.wav
│   │
│   ├───10_sample
│   │       guitar48_stereo_10_sample.wav
│   │
│   ├───1_sample
│   │       guitar48_stereo_1_sample.wav
│   │
│   ├───1_second
│   │       guitar48_stereo_1_sec.wav
│   │
│   └───5_second
│           guitar48_stereo_5_sec.wav
│
├───svr_training
│       training_mat_tcdaudio14_aacvopus15_fvnsims.txt
│       training_mat_tcdaudio14_aacvopus15_moslqs.txt
│
└───test_model
        cpp_model.txt
```

There are also entries like this (from visqol_manager_test):
```
[visqol_manager.cc : 65] RAW: INVALID_ARGUMENT: Failed to load the SVR model file: C:\users\USERNAME\_bazel_USERNAME\amczxuak\execroot\__main__\bazel-out\x64_windows-opt\bin\visqol_manager_test.exe.runfiles\__main__/model/libsvm_nu_svr_model.txt
```
This file is missing (there are no files under `C:\users\USERNAME\_bazel_USERNAME\amczxuak\execroot\__main__\bazel-out\x64_windows-opt\bin\visqol_manager_test.exe.runfiles\__main__/` )

Are there some other command line flags or other setup work required when running the tests on Windows? 

I'm happy to provide more detailed test logs if needed, or more version info.

**Comment by FeargusOG** [comment]
Hi @iUnknwn ,

Thanks for opening this issue. This is actually a known issue with `Bazel` on Windows. When I last worked on the Windows unit tests, there was no fix for this. However, I _think_ there might be a solution for this now. You can see this GitHub issues for more details:

- https://github.com/bazelbuild/bazel/issues/3726
- https://github.com/bazelbuild/bazel/issues/5807
- https://github.com/bazelbuild/rules_nodejs/issues/1689

Unfortunately, I no longer have access to a Windows machine for testing any of this. Please feel free to investigate and record any findings here or open a PR!

**Comment by iUnknwn** [comment]
Hi @FeargusOG - I'll investigate the issues you mentioned, and if I can figure out a way to resolve the issue I'll file a PR. 

In the interim, could you perhaps provide basic instructions to run some of the tests manually, such as what are expected scores with some of the sample files (to run as a sanity check post-build)?

**Comment by iUnknwn** [comment]
Good news - it looks like the tests are now working (I'm assuming that 'too big' error isn't critical, though feel free to correct me):

![image](https://user-images.githubusercontent.com/1129122/120693821-5a8b9880-c45e-11eb-8084-85f2d5412344.png)

The relevant bug appears to be this one here: https://github.com/bazelbuild/bazel/issues/8843 - if someone is on Windows 10 version 1703 or newer, and they've enabled Developer Mode, they can run the tests with: `bazel test all_unit_tests --enable_runfiles`

This will ensure that the test files are symbolically linked in the test directories. 

I'll try to submit a PR for the main readme with instructions either today or tomorrow.

**Comment by FeargusOG** [comment]
Hi @iUnknwn ,

That's great! Thanks for tracking that down and for the readme update. Apologies I didn't get back to you in the meantime with the test results!

**Comment by mchinen** [comment]
The latest windows build passes all c++ tests now.
