### ISSUE TITLE
Degraded audio sample rate: 0.

### ISSUE THREAD

**Issue by seba-plpl** [google/visqol#56]
Hi, I'm taking my first steps with visqol and have following problem:
I have two files (good and bad) both have 16kHz sample rate.
When i'm trying to compare this files, i have an error saing that degraded sample has 0 rate, as below:

C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\bazel-bin>visqol.exe --reference_file "C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\good_16000_Hz.wav" --degraded_file "C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\bad_16000_Hz.wav" --verbose --use_speech_mode --similarity_to_quality_model C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\model\libsvm_nu_svr_model.txt
[wav_reader.cc : 174] RAW: Error parsing WAV Header - Expected 16bit samples.
[misc_audio.cc : 143] RAW: Error reading header for file C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\good_16000_Hz.wav.
[wav_reader.cc : 174] RAW: Error parsing WAV Header - Expected 16bit samples.
[misc_audio.cc : 143] RAW: Error reading header for file C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\bad_16000_Hz.wav.
**[main.cc : 57] RAW: Error executing ViSQOL: INVALID_ARGUMENT: Input audio signals have different sample rates! Reference audio sample rate: 138441597507072. Degraded audio sample rate: 0.**

But, after changed sample rate of this files to 48kHz, it works, it can be compared with following result:

"C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\good1_16000_Hz.wav" --degraded_file "C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\bad1_16000_Hz.wav" --verbose --use_speech_mode --similarity_to_quality_model C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\model\libsvm_nu_svr_model.txt
**[visqol_manager.cc : 227] RAW: Input audio sample rate is above 16kHz, which may have undesired effects for speech mode.  Consider resampling to 16kHz.**
ViSQOL conformance version: 310
Speech mode

Reference Filepath:     C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\good1_16000_Hz.wav
Degraded Filepath:      C:\Users\user1\scoop\apps\bazel\4.2.1\visqol_test\visqol\testdata\clean_speech\mysample\bad1_16000_Hz.wav
MOS-LQO:                1.59276
--------------------------
|  FVNSIM  |  Freq Band  |
--------------------------
| 0.401463 |    50.000Hz |
| 0.490032 |    98.767Hz |
| 0.458079 |   156.063Hz |
| 0.417346 |   223.380Hz |
| 0.361086 |   302.471Hz |
| 0.430890 |   395.394Hz |
| 0.422619 |   504.570Hz |
| 0.387232 |   632.839Hz |
| 0.394989 |   783.543Hz |
| 0.428883 |   960.604Hz |
| 0.433549 |  1168.633Hz |
| 0.392224 |  1413.046Hz |
| 0.373587 |  1700.205Hz |
| 0.323136 |  2037.587Hz |
| 0.293950 |  2433.977Hz |
| 0.344104 |  2899.694Hz |
| 0.340415 |  3446.863Hz |
| 0.315738 |  4089.731Hz |
| 0.345335 |  4845.034Hz |
| 0.382120 |  5732.437Hz |
| 0.340726 |  6775.044Hz |
--------------------------

Can you please help me, what i'm doing wrong?

Mentioned files attached
[mysample.zip](https://github.com/google/visqol/files/7285305/mysample.zip)

Thans in advance

**Comment by mchinen** [comment]
Hm, how were these wav files created?  Possibly the waveform headers are not being parsed correctly.  One workaround would be to output these in audacity or FFMpeg (untransformed) at 16khz again, since those are known to work.

**Comment by mchinen** [comment]
Closing due to staleness. Feel free to reopen.
