### ISSUE TITLE
Duration of the Files

### ISSUE THREAD

**Issue by RHimaJyothi** [google/visqol#62]
What is the max file length(duration) we can pass to the VISQOL? Can we pass more than 8-10secs files? How it'll handle 2min input/output files?

**Comment by mchinen** [comment]
Our test uses a long duration file of 1 minute.  Probably 2 minutes will also run.  However, this is not preferred as the training data is all in the 8-10 second range.  Some users prefer to break the long file up into shorter segments for this kind of case.
