### ISSUE TITLE
visqol not found

### ISSUE THREAD

**Issue by jcn199729** [google/visqol#64]
![Inked155960571-6ae434c2-b0a1-4d2f-a386-572ee8afe9d0_LI](https://user-images.githubusercontent.com/58527362/155960911-2ffacb70-33c2-4b47-b645-183ea466531f.jpg)
Hi, I didn't found visqol under bazel-bin after building on Ubuntu, could you give any advice to fix this? Thanks

**Comment by mchinen** [comment]
Hi, can you tell me how you built it?  If you build the 'visqol' target (e.g. `bazel build :visqol`) it should be in bazel-bin.

**Comment by MaksymT17** [comment]
I found that with a longer duration, longer than 10 seconds, an application with Visqol may crash with Seg Fault.
The crash appears only when I use multiple threads, each of thread could run VisqolApi::Measure.
GDB backtrace I caught several times

memcpy@@GLIBC_2.14 (vg_replace_strmem.c:1035)
Visqol::AMatrix<double>::AMatrix(absl...
Visqol::VisqolApi::Measure:


And it is important in our use case.
After reading documentation of Visqol and documented code I didnt see mentions that measure of MOS value is thread safe.
Of course I can add mutex or signal handler.

@mchinen , may I ask you,
Just to be sure that Im using Visqol api correctly, can we assume the current implementation of Visqol could be safely called from a single thread? with multiple threads we would need to apply synchronization
