### ISSUE TITLE
Gammatome 

### ISSUE THREAD

**Issue by listener17** [google/visqol#7]
I saw in the code reference to Dan Ellis’s Gammatone spectrogram: https://labrosa.ee.columbia.edu/matlab/gammatonegram/ 
Which version of Gammatone spectrogram of Dan Ellis was used? Fast one or the accurate one?

**Comment by mchinen** [comment]
I did not author that code, but IIRC it uses the time domain only to compute the gammatone spectrogram (does not use an FFT), which seems to be the accurate one.
